version: "3.9"

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: hirebot-backend
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    networks:
      - hirebot-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.frontend
    container_name: hirebot-frontend
    ports:
      - "5173:80"
    networks:
      - hirebot-network

networks:
  hirebot-network:
    driver: bridge
